name: perapal
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  animated_splash_screen: ^1.1.0
  firebase_core: ^2.31.0
  provider: ^5.0.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.5
  shared_preferences: ^2.2.3
  flutter_svg: ^2.0.0
  country_flags: ^2.2.0
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/